spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0:
          destination: notification-events

server:
  port: 3111

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}:${random.uuid}
